## 1.DataFrame的创建

In [1]:
from tokenize import group

import pandas as pd

# 通过series来创建
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
df = pd.DataFrame({"第1列": s1, "第2列": s2})

# 通过字典来创建
df = pd.DataFrame(
    {
        "name": ["tom", 'jack', 'alice', 'bob', 'allen'],
        "age": [15, 17, 20, 26, 30],
        "score": [60.5, 80, 30.6, 70, 83.5]
    }, index=[1, 2, 3, 4, 5], columns=["name", "score", "age"]
)
df

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

## 2.DataFrame的属性

In [2]:
print('行索引：')
print(df.index)
print('列标签：')
print(df.columns)
print('值')
print(df.values)

行索引：
Index([1, 2, 3, 4, 5], dtype='int64')
列标签：
Index(['name', 'score', 'age'], dtype='str')
值
[['tom' 60.5 15]
 ['jack' 80.0 17]
 ['alice' 30.6 20]
 ['bob' 70.0 26]
 ['allen' 83.5 30]]

In [3]:
print('维度：', df.ndim)
print('形状:', df.shape)
print('元素个数：', df.size)
print('数据类型：')
print(df.dtypes)

维度： 2
形状: (5, 3)
元素个数： 15
数据类型：
name         str
score    float64
age        int64
dtype: object

In [4]:
# 行列转置
print(df.T)

          1     2      3     4      5
name    tom  jack  alice   bob  allen
score  60.5  80.0   30.6  70.0   83.5
age      15    17     20    26     30

In [5]:
# 获取元素 loc  iloc  at  iat
# 某行
print(df.loc[4])
print(df.iloc[3])

name      bob
score    70.0
age        26
Name: 4, dtype: object
name      bob
score    70.0
age        26
Name: 4, dtype: object

In [6]:
# 某列
print(df.loc[:, 'name'])
print(df.iloc[:, 0])

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str

In [7]:
# 单个元素
print(df.at[3, 'score'])
print(df.iat[2, 1])
print(df.loc[3, 'score'])
print(df.iloc[2, 1])

30.6
30.6
30.6
30.6

In [8]:
# 获取单列数据
print(df['name'])
print(type(df['name']))
print(df.name)
print(type(df.name))
print(df[['name']])
print(type(df[['name']]))
print(df[['name', 'score']])

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
<class 'pandas.Series'>
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
<class 'pandas.Series'>
    name
1    tom
2   jack
3  alice
4    bob
5  allen
<class 'pandas.DataFrame'>

    name
1    tom
2   jack
3  alice
4    bob
5  allen

In [10]:
# 使用布尔索引筛选数据
df[(df['score'] > 70) & (df.age < 20)]

   name  score  age
2  jack   80.0   17

In [11]:
# 随机抽样
df.sample(3)

    name  score  age
3  alice   30.6   20
1    tom   60.5   15
4    bob   70.0   26

## 3.DataFrame方法

In [ ]:
df = pd.DataFrame(
    {
        "name": ["tom", 'jack', 'alice', 'bob', 'allen'],
        "age": [15, 17, 20, 26, 30],
        "score": [60.5, 80, 30.6, 70, 83.5]
    }, index=[1, 2, 3, 4, 5], columns=["name", "score", "age"]
)

In [12]:
print(df.head())  #查看前n行数据，默认是5行
print(df.tail(1))  #查看后n行数据，默认是5行

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30
    name  score  age
5  allen   83.5   30

In [13]:
print(df.isin(['jack', 20]))  #查看单元格元素是否在列表中

    name  score    age
1  False  False  False
2   True  False  False
3  False  False   True
4  False  False  False
5  False  False  False

In [14]:
print(df.isna())  # 检查缺失值

    name  score    age
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [15]:
print(df['score'].sum())  #某一列的总和
print(df.score.max())  #最大值
print(df.age.min())  #最小值
print(df.score.mean())  #平均数
print(df.score.median())  #中位数
print(df.age.mode())  #众数

324.6
83.5
15
64.92
70.0
0    15
1    17
2    20
3    26
4    30
Name: age, dtype: int64

In [ ]:
df = pd.DataFrame(
    {
        "name": ["tom", "tom", 'jack', 'alice', 'bob', 'allen'],
        "age": [15, 15, 15, 20, 26, 30],
        "score": [60.5, 60.5, 80, 30.6, 70, 83.5]
    }, index=[1, 2, 3, 4, 5, 6], columns=["name", "score", "age"]
)

In [17]:
print(df.score.std())  #标准差
print(df.score.var())  #方差
print(df.score.quantile(0.25))  #分位数

21.188605428390044
448.957
60.5

In [18]:
print(df.describe())  # 描述信息

           score        age
count   5.000000   5.000000
mean   64.920000  21.600000
std    21.188605   6.268971
min    30.600000  15.000000
25%    60.500000  17.000000
50%    70.000000  20.000000
75%    80.000000  26.000000
max    83.500000  30.000000

In [19]:
print(df.count())  #每列非缺失值计数

name     5
score    5
age      5
dtype: int64

In [23]:
print(df.value_counts())  # 相同行数据计数

name   score  age
tom    60.5   15     1
jack   80.0   17     1
alice  30.6   20     1
bob    70.0   26     1
allen  83.5   30     1
Name: count, dtype: int64

In [24]:
print(df.drop_duplicates())  # 删除重复行

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [25]:
print(df.replace(15, 30))  # 替换

    name  score  age
1    tom   60.5   30
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [26]:
df.cumsum()  # 前缀和

                   name  score  age
1                   tom   60.5   15
2               tomjack  140.5   32
3          tomjackalice  171.1   52
4       tomjackalicebob  241.1   78
5  tomjackaliceboballen  324.6  108

In [27]:
print(df.sort_index(ascending=False))  # 排序

    name  score  age
5  allen   83.5   30
4    bob   70.0   26
3  alice   30.6   20
2   jack   80.0   17
1    tom   60.5   15

In [ ]:
print(df.sort_values(by='score'))

In [ ]:
df = pd.DataFrame(
    {
        "name": ["tom", "tom", 'jack', 'alice', 'bob', 'allen'],
        "age": [15, 15, 15, 20, 26, 30],
        "score": [60.5, 60.5, 80, 30.6, 70, 80]
    }, index=[1, 2, 3, 4, 5, 6], columns=["name", "score", "age"]
)

In [28]:
print(df.sort_values(by=['score', 'age'], ascending=[True, False]))

    name  score  age
3  alice   30.6   20
1    tom   60.5   15
4    bob   70.0   26
2   jack   80.0   17
5  allen   83.5   30

In [29]:
df.nlargest(2, columns=['score', 'age'])
df.nsmallest(2, columns=['score', 'age'])

    name  score  age
3  alice   30.6   20
1    tom   60.5   15

In [42]:
'''
案例1：学生成绩分析
场景：某班级的学生成绩数据如下，请完成以下任务：
1. 计算每位学生的总分和平均分。
2. 找出数学成绩高于90分或英语成绩高于85分的学生。
3. 按总分从高到低排序，并输出前3名学生。
'''

data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '数学': [85, 92, 78, 88, 95],
    '英语': [90, 88, 85, 92, 80],
    '物理': [75, 80, 88, 85, 90]
}
scores = pd.DataFrame(data)

# 计算每位学生的总分和平均分。
scores['总分'] = scores[['数学', '英语', '物理']].sum(axis=1)
scores['平均分'] = scores['总分'] / 3
# 找出数学成绩高于90分或英语成绩高于85分的学生。
print(scores[(scores['数学'] > 90) | (scores['英语'] > 85)])
# 按总分从高到低排序，并输出前3名学生。
scores.sort_values(by='总分', ascending=False).head(3)
scores.nlargest(3, columns='总分')

   姓名  数学  英语  物理   总分        平均分
0  张三  85  90  75  250  83.333333
1  李四  92  88  80  260  86.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

   姓名  数学  英语  物理   总分        平均分
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667

In [43]:
'''
案例2：销售数据分析
场景：某公司销售数据如下，请完成以下任务：
1. 计算每种产品的总销售额（销售额 = 单价 × 销量）。
2. 找出销售额最高的产品。
3. 按销售额从高到低排序，并输出所有产品信息。
'''

data = {
    '产品名称': ['A', 'B', 'C', 'D'],
    '单价': [100, 150, 200, 120],
    '销量': [50, 30, 20, 40]
}
df = pd.DataFrame(data)
df['总销售额'] = df['单价'] * df['销量']
df.nlargest(1, columns=['总销售额'])
df.sort_values('总销售额', ascending=False)

  产品名称   单价  销量  总销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000

In [57]:
'''
案例3：电商用户行为分析
场景：某电商平台的用户行为数据如下，请完成以下任务：
1. 计算每位用户的总消费金额（消费金额 = 商品单价 × 购买数量）
2. 找出消费金额最高的用户，并输出其所有信息
3. 计算所有用户的平均消费金额（保留2位小数）
4. 统计电子产品的总购买数量
'''
data = {
    '用户ID': [101, 102, 103, 104, 105],
    '用户名': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    '商品类别': ['电子产品', '服饰', '电子产品', '家居', '服饰'],
    '商品单价': [1200, 300, 800, 150, 200],
    '购买数量': [1, 3, 2, 5, 4]
}
df = pd.DataFrame(data)
# 计算每位用户的总消费金额
df['总消费金额'] = df['商品单价'] * df['购买数量']
consume_amount = df.groupby('用户ID')['总消费金额'].sum()
# 找出消费金额最高的用户，并输出其所有信息
df.nlargest(1, columns=['总消费金额'])
# 统计所有用户的平均消费金额（保留2位小数）
consume_amount.mean()
# 统计电子产品的总购买数量
df[df['商品类别'] == '电子产品']['购买数量'].sum()

np.int64(3)