In [6]:
import pandas as pd

pd.set_option('display.min_rows', 30)  # 设置显示行数

df = pd.read_csv('data/sales.csv')

# 处理缺失值
# 查看缺失值
df.isnull()

# 删除缺失值
df.dropna()  #删除行
df.dropna(axis=1)  #删除列

# 填充缺失值
df.fillna('未知')  #填充指定值
df.ffill()  #填充上一行数据
df.bfill()  #填充下一行数据

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199     合肥   支付宝  2025/06/01
1    5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3    6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19     广州  微信支付  2025-06-02
5    5897064217    图书    字帖     4  -29     广州    现金  2025-06-02
6    6857752388    服装    袜子     7   29     郑州    现金  2025-06-02
7    6898807429    服装    T恤     6  199     武汉   银行卡  2025-06-02
8    5875402232  电子产品   路由器     9  299     福州   银行卡  2025-06-03
9    5888085059    图书    字典     2   99     青岛  微信支付  2025-06-04
10   5808071569    食品   矿泉水     9   29     重庆   支付宝  2025-06-04
11   6890234923  家居用品  餐具套装    10  199     武汉    现金  2025-06-04
12   5891597362  电子产品    鼠标     3   89     合肥   银行卡  2025-06-04
13   6880065056    图书   练习册     8   39     深圳   支付宝  2025-06-04
14   5804178086  电子产品  蓝牙耳机    10  199     重庆  微信支付  2025-06-04
..          ...   ...   ...   ...  ...    ...   ...         ...
985  5862231814    服装    毛衣     6  399     厦门  微信支付  2026-03-15
986  5877750266    图书    绘本     1   59     北京   银行卡  2026-03-15
987  6869062683  电子产品  游戏手柄     1  249     长沙   银行卡  2026-03-15
988  6845708709    服装    衬衫     7  299     苏州   支付宝  2026-03-16
989  6879395963    图书   散文集     4   59     长沙   支付宝  2026-03-18
990  6809488145  电子产品  移动电源     6  149     福州   支付宝  2026-03-18
991  6881691632  家居用品    纸巾    10   39     天津   银行卡  2026-03-19
992  5852186744  电子产品  蓝牙耳机     2  199     广州  微信支付  2026-03-19
993  6870828210    服装    内衣     8   89     广州  微信支付  2026-03-20
994  5860722276    服装    外套     6  599     广州  微信支付  2026-03-20
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89     西安   银行卡  2026-03-20

[1000 rows x 8 columns]

In [10]:
#处理重复值
#查看重复值
df.duplicated()  #默认两行完全相同才算重复
df.duplicated(subset=['订单号'])  #指定判重列

# 删除重复值
df.drop_duplicates(subset=['订单号'], keep='first')

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3    6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19    NaN  微信支付  2025-06-02
5    5897064217    图书    字帖     4   29     广州    现金  2025-06-02
6    6857752388    服装    袜子     7   29     郑州    现金  2025-06-02
7    6898807429    服装    T恤     6  199     武汉   银行卡  2025-06-02
8    5875402232  电子产品   路由器     9  299     福州   银行卡  2025-06-03
10   5808071569    食品   矿泉水     9   29     重庆   支付宝  2025-06-04
11   6890234923  家居用品  餐具套装    10  199     武汉    现金  2025-06-04
12   5891597362  电子产品    鼠标     3   89     合肥   银行卡  2025-06-04
13   6880065056    图书   练习册     8   39     深圳   支付宝  2025-06-04
14   5804178086  电子产品  蓝牙耳机    10  199     重庆  微信支付  2025-06-04
15   5878551159    图书   练习册     5   39     重庆    现金  2025-06-05
..          ...   ...   ...   ...  ...    ...   ...         ...
985  5862231814    服装    毛衣     6  399     厦门  微信支付  2026-03-15
986  5877750266    图书    绘本     1   59     北京   银行卡  2026-03-15
987  6869062683  电子产品  游戏手柄     1  249     长沙   银行卡  2026-03-15
988  6845708709    服装    衬衫     7  299     苏州   支付宝  2026-03-16
989  6879395963    图书   散文集     4   59     长沙   支付宝  2026-03-18
990  6809488145  电子产品  移动电源     6  149     福州   支付宝  2026-03-18
991  6881691632  家居用品    纸巾    10   39     天津   银行卡  2026-03-19
992  5852186744  电子产品  蓝牙耳机     2  199     广州  微信支付  2026-03-19
993  6870828210    服装    内衣     8   89     广州  微信支付  2026-03-20
994  5860722276    服装    外套     6  599     广州  微信支付  2026-03-20
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89     西安   银行卡  2026-03-20

[999 rows x 8 columns]

In [6]:
# 处理异常值
# 查看异常值
df[df['单价'] < 0]

# 删除异常值
df.drop(df[df['单价'] < 0].index)

# 修复异常值
df['单价']=df['单价'].abs()
df

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3    6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19    NaN  微信支付  2025-06-02
5    5897064217    图书    字帖     4   29     广州    现金  2025-06-02
6    6857752388    服装    袜子     7   29     郑州    现金  2025-06-02
7    6898807429    服装    T恤     6  199     武汉   银行卡  2025-06-02
8    5875402232  电子产品   路由器     9  299     福州   银行卡  2025-06-03
9    5888085059    图书    字典     2   99     青岛  微信支付  2025-06-04
10   5808071569    食品   矿泉水     9   29     重庆   支付宝  2025-06-04
11   6890234923  家居用品  餐具套装    10  199     武汉    现金  2025-06-04
12   5891597362  电子产品    鼠标     3   89     合肥   银行卡  2025-06-04
13   6880065056    图书   练习册     8   39     深圳   支付宝  2025-06-04
14   5804178086  电子产品  蓝牙耳机    10  199     重庆  微信支付  2025-06-04
..          ...   ...   ...   ...  ...    ...   ...         ...
985  5862231814    服装    毛衣     6  399     厦门  微信支付  2026-03-15
986  5877750266    图书    绘本     1   59     北京   银行卡  2026-03-15
987  6869062683  电子产品  游戏手柄     1  249     长沙   银行卡  2026-03-15
988  6845708709    服装    衬衫     7  299     苏州   支付宝  2026-03-16
989  6879395963    图书   散文集     4   59     长沙   支付宝  2026-03-18
990  6809488145  电子产品  移动电源     6  149     福州   支付宝  2026-03-18
991  6881691632  家居用品    纸巾    10   39     天津   银行卡  2026-03-19
992  5852186744  电子产品  蓝牙耳机     2  199     广州  微信支付  2026-03-19
993  6870828210    服装    内衣     8   89     广州  微信支付  2026-03-20
994  5860722276    服装    外套     6  599     广州  微信支付  2026-03-20
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89     西安   银行卡  2026-03-20

[1000 rows x 8 columns]

In [7]:
# 处理格式
df['订单日期']=df['订单日期'].str.replace('/','-')
df

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3    6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19    NaN  微信支付  2025-06-02
5    5897064217    图书    字帖     4  -29     广州    现金  2025-06-02
6    6857752388    服装    袜子     7   29     郑州    现金  2025-06-02
7    6898807429    服装    T恤     6  199     武汉   银行卡  2025-06-02
8    5875402232  电子产品   路由器     9  299     福州   银行卡  2025-06-03
9    5888085059    图书    字典     2   99     青岛  微信支付  2025-06-04
10   5808071569    食品   矿泉水     9   29     重庆   支付宝  2025-06-04
11   6890234923  家居用品  餐具套装    10  199     武汉    现金  2025-06-04
12   5891597362  电子产品    鼠标     3   89     合肥   银行卡  2025-06-04
13   6880065056    图书   练习册     8   39     深圳   支付宝  2025-06-04
14   5804178086  电子产品  蓝牙耳机    10  199     重庆  微信支付  2025-06-04
..          ...   ...   ...   ...  ...    ...   ...         ...
985  5862231814    服装    毛衣     6  399     厦门  微信支付  2026-03-15
986  5877750266    图书    绘本     1   59     北京   银行卡  2026-03-15
987  6869062683  电子产品  游戏手柄     1  249     长沙   银行卡  2026-03-15
988  6845708709    服装    衬衫     7  299     苏州   支付宝  2026-03-16
989  6879395963    图书   散文集     4   59     长沙   支付宝  2026-03-18
990  6809488145  电子产品  移动电源     6  149     福州   支付宝  2026-03-18
991  6881691632  家居用品    纸巾    10   39     天津   银行卡  2026-03-19
992  5852186744  电子产品  蓝牙耳机     2  199     广州  微信支付  2026-03-19
993  6870828210    服装    内衣     8   89     广州  微信支付  2026-03-20
994  5860722276    服装    外套     6  599     广州  微信支付  2026-03-20
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89     西安   银行卡  2026-03-20

[1000 rows x 8 columns]